name: GitHubActions CI tests

on:
  push:
    branches: [master, dev, ci]
  pull_request:

jobs:
  build-nix:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        build_suite: [autoconf]
        with_coveralls: [no]
        include:
          # Do one build with cmake instead of autoconf
          - os: ubuntu-20.04
            build_suite: cmake
            with_coveralls: no
          # And run one build with gcov and coveralls
          # (Does currently not work, but neither did it in travis)
          #- os: ubuntu-20.04
          #  build_suite: autoconf
          #  with_coveralls: yes
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install deps
        run: |
          if (echo "${{ matrix.os }}" | grep -qE '^macos-') ; then
            #brew update
            # freetype, gettext, icuc4 and autoconf are preinstalled
            # and `brew install` fails if a non-uptodate version is already installed
            #brew upgrade autoconf freetype gettext icu4c
            brew install automake boost ffmpeg ffms2 fftw fribidi libass \
                         lua luarocks m4 wxmac hunspell uchardet
            # Use bundled googletest
            git submodule --quiet init
            git submodule --quiet update vendor/googletest
            # Upgrade wxMac to 3.1
            pushd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/
            patch -p1 << EOF
          diff --git a/Formula/wxmac.rb b/Formula/wxmac.rb
          index 60dd92c233..80ac488152 100644
          --- a/Formula/wxmac.rb
          +++ b/Formula/wxmac.rb
          @@ -1,10 +1,9 @@
           class Wxmac < Formula
             desc "Cross-platform C++ GUI toolkit (wxWidgets for macOS)"
             homepage "https://www.wxwidgets.org"
          -  url "https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.5.1/wxWidgets-3.0.5.1.tar.bz2"
          -  sha256 "440f6e73cf5afb2cbf9af10cec8da6cdd3d3998d527598a53db87099524ac807"
          +  url "https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.4/wxWidgets-3.1.4.tar.bz2"
          +  sha256 "3ca3a19a14b407d0cdda507a7930c2e84ae1c8e74f946e0144d2fa7d881f1a94"
             license "wxWindows"
          -  revision 1
             head "https://github.com/wxWidgets/wxWidgets.git"

             livecheck do
          @@ -52,8 +51,8 @@ class Wxmac < Formula
                 "--disable-precomp-headers",
                 # This is the default option, but be explicit
                 "--disable-monolithic",
          -      # Set with-macosx-version-min to avoid configure defaulting to 10.5
          -      "--with-macosx-version-min=#{MacOS.version}",
          +      # Set with-macosx-version-min to 10.11 if you are building package for distribution
          +      "--with-macosx-version-min=10.11",
               ]

               system "./configure", *args
          EOF
            popd
            brew reinstall --build-from-source wxmac
          else
            #sudo apt-get update && sudo apt-get upgrade -y
            sudo apt-get update && sudo apt-get install -y --no-install-recommends ${{ matrix.build_suite }} \
              autopoint build-essential g++ gcc gettext libasound2-dev \
              libass-dev  libffms2-dev libfftw3-dev libfontconfig1-dev   \
              libfribidi-dev libgtest-dev libhunspell-dev libicu-dev libopenal-dev       \
              libpulse-dev libuchardet-dev libwxgtk3.0-gtk3-dev luarocks portaudio19-dev \
              python3-pip python3-setuptools \
              pkg-config libgl1-mesa-dev libgl-dev libfreetype6-dev libfontconfig-dev \
              intltool libboost-all-dev googletest
            if [ "x${{ matrix.with_coveralls }}" = "xyes" ] ; then
              sudo pip3 install -U cpp-coveralls
            fi
            if [ "x${{ matrix.build_suite }}" = "xautoconf" ] ; then
              # Use system provided googletest via source
              # (CMake will precompile it and use the binaries)
              rm -fr vendor/googletest
              cp -R /usr/src/googletest/googletest vendor/
            fi
          fi

          sudo luarocks install busted     > /dev/null
          sudo luarocks install moonscript > /dev/null
          sudo luarocks install uuid       > /dev/null

      - name: set up MacOS env
        if: ${{ startsWith( matrix.os, 'macos-' ) }}
        run: |
          # Changes are only available in the following steps, not the current one
          echo 'CPPFLAGS=-I/usr/local/opt/gettext/include -I/usr/local/opt/icu4c/include' >> $GITHUB_ENV
          echo 'LDFLAGS=-L/usr/local/opt/gettext/lib -L/usr/local/opt/icu4c/lib' >> $GITHUB_ENV
          echo 'PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig' >> $GITHUB_ENV
          echo 'ACLOCAL_PATH=/usr/local/opt/gettext/share/aclocal'  >> $GITHUB_ENV
          # Prepend to $PATH
          echo "/usr/local/opt/icu4c/bin"   >> $GITHUB_PATH
          echo "/usr/local/opt/icu4c/sbin"  >> $GITHUB_PATH
          echo "/usr/local/opt/gettext/bin" >> $GITHUB_PATH

      - name: set up coverage env
        if: ${{ matrix.with_coveralls == 'yes' }}
        run: |
          echo "CPPFLAGS=--coverage $CPPFLAGS" >> $GITHUB_ENV
          echo "LIBS=-lgcov $LIBS" >> $GITHUB_ENV

      - name: configure
        run: |
          if [ "x${{ matrix.build_suite }}" = "xautoconf" ] ; then
            ./autogen.sh
            conf_success=0
            ./configure --enable-debug || conf_success=1
            [ "$conf_success" -eq 0 ] || (cat config.log; exit 1)
          else
            mkdir build-dir
            cd build-dir
            cmake -DCMAKE_CXX_FLAGS='-Wall -Wextra -Wno-unused-parameter -pedantic' -DCMAKE_C_FLAGS='-Wall -Wextra -Wno-unused-parameter' -DWITH_STARTUPLOG=ON -DWITH_TEST=ON  ..
          fi

      - name: build
        run: |
          [ "x${{ matrix.build_suite }}" = "xautoconf" ] || cd build-dir
          make -j 2

      - name: run tests
        run: |
          [ "x${{ matrix.build_suite }}" = "xautoconf" ] || cd build-dir
          make test

      - name: coveralls
        if: ${{ matrix.with_coveralls == 'yes' }}
        run: |
          coveralls --exclude vendor --exclude src --exclude build \
                    --exclude tools --exclude libaegisub/windows \
                    > /dev/null

      - name: package
        if: ${{ startsWith( matrix.os, 'macos-' ) }}
        run: |
          make osx-dmg
          mv *.dmg aegisub-macos-GHA.dmg

      - name: upload artifact
        if: ${{ startsWith( matrix.os, 'macos-' ) }}
        uses: actions/upload-artifact@v2
        with:
          name: aegisub-macos-GHA
          path: aegisub-macos-GHA.dmg

  build-win:
    runs-on: windows-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: cache vcpkg packages
      uses: actions/cache@v2
      with:
        path: C:\vcpkg\installed
        key: vcpkg-installed-x64-windows

    - name: install deps
      run: |
        Invoke-WebRequest -Uri https://github.com/FFMS/ffms2/releases/download/2.23/ffms2-2.23.1-msvc.7z -OutFile vendor/ffms2-2.23.1-msvc.7z
        Invoke-WebRequest -Uri https://globalcdn.nuget.org/packages/microsoft.xaudio2.redist.1.2.6.nupkg -OutFile vendor/microsoft.xaudio2.redist.1.2.6.nupkg

        7z.exe x vendor/ffms2-2.23.1-msvc.7z -ovendor/ffms2
        7z.exe x vendor/microsoft.xaudio2.redist.1.2.6.nupkg -ovendor/xaudio2

        vcpkg.exe install --triplet x64-windows avisynthplus boost-asio boost-container boost-crc boost-filesystem boost-flyweight boost-gil boost-interprocess 'boost-locale[icu]' 'boost-regex[icu]' boost-scope-exit boost-thread fftw3 hunspell icu libass libiconv uchardet wxwidgets gtest
        Remove-Item –Path C:\vcpkg\installed\x64-windows\debug –Recurse -ErrorAction Continue
        Remove-Item –Path C:\vcpkg\installed\x64-windows\share\expat\expat-debug.cmake -ErrorAction Continue
        Remove-Item –Path C:\vcpkg\installed\x64-windows\share\GTest\GTestTargets-debug.cmake -ErrorAction Continue
        Remove-Item –Path C:\vcpkg\installed\x64-windows\share\liblzma\liblzmaTargets-debug.cmake -ErrorAction Continue
        Remove-Item –Path C:\vcpkg\installed\x64-windows\share\libpng\libpng-targets-debug.cmake -ErrorAction Continue

    - name: configure
      run: |
        bash.exe build/version.sh .
        New-Item -Path build-dir -ItemType directory
        Set-Location build-dir
        cmake.exe '-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake' '-DAviSynth_SHARED_LIBRARY=C:/vcpkg/installed/x64-windows/bin/AviSynth.dll' '-DFFMS2_INCLUDE_DIRS=../vendor/ffms2/ffms2-2.23.1-msvc/include' '-DFFMS2_LIBRARIES=../vendor/ffms2/ffms2-2.23.1-msvc/x64/ffms2.lib' '-DXAUDIO2_REDIST=ON' '-DXAudio2redist_INCLUDE_DIRS=../vendor/xaudio2/build/native/include' '-DXAudio2redist_LIBRARIES=../vendor/xaudio2/build/native/release/lib/x64/xaudio2_9redist.lib' '-DCMAKE_CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /DUNICODE /D_UNICODE /MP' '-DCMAKE_C_FLAGS=/DWIN32 /D_WINDOWS /DUNICODE /D_UNICODE /MP' '-DWITH_TEST=ON' ..

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: build
      run: |
        Set-Location build-dir
        MSBuild.exe Aegisub.vcxproj -p:Configuration=Release

    - name: run tests
      run: |
        Set-Location build-dir
        MSBuild.exe test.vcxproj -p:Configuration=Release

    - name: package
      run: |
        Invoke-WebRequest -Uri https://github.com/wangqr/Aegisub/releases/download/v3.3.2/Aegisub-3.3.2-win64.zip -OutFile vendor/aegisub332.zip
        Invoke-WebRequest -Uri https://ftp.wangqr.tk/aegisub/aegisub-win64-cmake-20210405-r9185.zip -OutFile vendor/aegisub9185.zip

        7z.exe x vendor/aegisub332.zip -ovendor/aegisub332
        7z.exe x vendor/aegisub9185.zip -ovendor/aegisub9185

        Move-Item -Path build-dir\Release\Aegisub.exe -Destination build-dir\Aegisub.exe
        Remove-Item -Path build-dir\Release\*.exp,build-dir\Release\*.lib,build-dir\Release\*.exe
        Move-Item -Path build-dir\Aegisub.exe -Destination build-dir\Release\Aegisub.exe
        New-Item -Path build-dir\Release\automation -ItemType directory
        Copy-Item -Path automation\autoload,automation\demos,automation\include -Destination build-dir\Release\automation -Recurse

        Copy-Item -Path C:\vcpkg\installed\x64-windows\bin\AviSynth.dll -Destination build-dir\Release
        Copy-Item -Path vendor\ffms2\ffms2-2.23.1-msvc\x64\ffms2.dll -Destination build-dir\Release
        Copy-Item -Path vendor\xaudio2\build\native\release\bin\x64\xaudio2_9redist.dll -Destination build-dir\Release
        Copy-Item -Path vendor\aegisub332\dictionaries,vendor\aegisub332\licenses,vendor\aegisub332\locale,vendor\aegisub332\AssDraw3.exe,vendor\aegisub332\AssDraw3.chm,vendor\aegisub332\DirectShowSource.dll -Destination build-dir\Release -Recurse
        Copy-Item -Path vendor\aegisub9185\csri -Destination build-dir\Release -Recurse

    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: aegisub-win64-cmake-GHA
        path: build-dir/Release
